//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gobbi.CoreServices.Properties
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gobbi.CoreServices.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha y hora no puede ser menor a la actual..
        /// </summary>
        internal static string ERROR_ABSOLUTETIMERANGE {
            get {
                return ResourceManager.GetString("ERROR_ABSOLUTETIMERANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra el &quot;DefaultAuthorizationProviderName&quot; de Authorization.
        /// </summary>
        internal static string ERROR_AUTHORIZATIONFACTORY_INVALIDDEFAULTPROVIDERNAME {
            get {
                return ResourceManager.GetString("ERROR_AUTHORIZATIONFACTORY_INVALIDDEFAULTPROVIDERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra el &quot;DefaultEvaPrincipalName&quot; de EVA Principal Porvider.
        /// </summary>
        internal static string ERROR_EvaPRINCIPALFACTORY_INVALIDDEFAULTNAME {
            get {
                return ResourceManager.GetString("ERROR_EvaPRINCIPALFACTORY_INVALIDDEFAULTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra el &quot;DefaultCacheManagerName&quot; de Caching.
        /// </summary>
        internal static string ERROR_CACHEFACTORY_INVALIDDEFAULTCACHEMANAGERNAME {
            get {
                return ResourceManager.GetString("ERROR_CACHEFACTORY_INVALIDDEFAULTCACHEMANAGERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la configuración para &apos;{0}&apos;.
        /// </summary>
        internal static string ERROR_CONFIGURATIONNOTDEFINED {
            get {
                return ResourceManager.GetString("ERROR_CONFIGURATIONNOTDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No està definida la connectionStringSettings para &quot;{0}&quot;..
        /// </summary>
        internal static string ERROR_CONNECTIONSTRINGSETTINGS_NULL {
            get {
                return ResourceManager.GetString("ERROR_CONNECTIONSTRINGSETTINGS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ConnectionString de &quot;{0}&quot; no es válida..
        /// </summary>
        internal static string ERROR_CONNECTIONSTRINGSSECTION_CONNECTIONSTRING_NULL {
            get {
                return ResourceManager.GetString("ERROR_CONNECTIONSTRINGSSECTION_CONNECTIONSTRING_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No está definida la sección connectionStrings.
        /// </summary>
        internal static string ERROR_CONNECTIONSTRINGSSECTION_NULL {
            get {
                return ResourceManager.GetString("ERROR_CONNECTIONSTRINGSSECTION_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La configuración es incorrecta para &quot;{0}&quot;..
        /// </summary>
        internal static string ERROR_DATABASEFACTORY_BADCONFIGURATION {
            get {
                return ResourceManager.GetString("ERROR_DATABASEFACTORY_BADCONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parámentro no puede ser nulo o cadena vacía..
        /// </summary>
        internal static string ERROR_EMPTYPARAMETERNAME {
            get {
                return ResourceManager.GetString("ERROR_EMPTYPARAMETERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo una falla al escribir la entrada de log en &quot;{0}&quot;..
        /// </summary>
        internal static string ERROR_EVENTCUSTOMTRACELISTENER_WRITEFAILURE {
            get {
                return ResourceManager.GetString("ERROR_EVENTCUSTOMTRACELISTENER_WRITEFAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra la sección de configuración &quot;{0}&quot; para el manejo de excepciones..
        /// </summary>
        internal static string ERROR_EXCEPTIONPOLICY_CONFIGURATIONNOTFOUND {
            get {
                return ResourceManager.GetString("ERROR_EXCEPTIONPOLICY_CONFIGURATIONNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron políticas en la configuración..
        /// </summary>
        internal static string ERROR_EXCEPTIONPOLICY_NOTPOLICIESDEFINED {
            get {
                return ResourceManager.GetString("ERROR_EXCEPTIONPOLICY_NOTPOLICIESDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la política &quot;{0}&quot;..
        /// </summary>
        internal static string ERROR_EXCEPTIONPOLICY_POLICYNOTFOUND {
            get {
                return ResourceManager.GetString("ERROR_EXCEPTIONPOLICY_POLICYNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La política &quot;{0}&quot; no tiene definida acciones para la excepciones del tipo &quot;{1}&quot;..
        /// </summary>
        internal static string ERROR_EXCEPTIONPOLICYIMPL_NOTHANDLERDEFINED {
            get {
                return ResourceManager.GetString("ERROR_EXCEPTIONPOLICYIMPL_NOTHANDLERDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los manejadores de excepción &quot;{0}&quot; no generaron ninguna excepción..
        /// </summary>
        internal static string ERROR_EXCEPTIONTYPEIMPL_EXCEPTIONTOTHROWNOTFOUND {
            get {
                return ResourceManager.GetString("ERROR_EXCEPTIONTYPEIMPL_EXCEPTIONTOTHROWNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede parar antes si no ha comenzado..
        /// </summary>
        internal static string ERROR_EXPIRATIONPOLLTIMER_INVALIDSTOPOPERATION {
            get {
                return ResourceManager.GetString("ERROR_EXPIRATIONPOLLTIMER_INVALIDSTOPOPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tiempo de expiración debe ser por lo menos 1 segundo..
        /// </summary>
        internal static string ERROR_EXPIRATIONPOLLTIMER_INVALIDTIME {
            get {
                return ResourceManager.GetString("ERROR_EXPIRATIONPOLLTIMER_INVALIDTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El largo del formato es inválido..
        /// </summary>
        internal static string ERROR_EXTENDEDFORMATINVALIDARGUMENTS {
            get {
                return ResourceManager.GetString("ERROR_EXTENDEDFORMATINVALIDARGUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeFormat no puede ser nulo..
        /// </summary>
        internal static string ERROR_EXTENDEDFORMATNULLTIMEFORMAT {
            get {
                return ResourceManager.GetString("ERROR_EXTENDEDFORMATNULLTIMEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Día de la semana en ExtendedFormat fuera de rango..
        /// </summary>
        internal static string ERROR_EXTENDEDFORMATRANGEDAYS {
            get {
                return ResourceManager.GetString("ERROR_EXTENDEDFORMATRANGEDAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas en ExtendedFormat fuera de rango..
        /// </summary>
        internal static string ERROR_EXTENDEDFORMATRANGEHOURS {
            get {
                return ResourceManager.GetString("ERROR_EXTENDEDFORMATRANGEHOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutos en ExtendedFormat fuera de rango..
        /// </summary>
        internal static string ERROR_EXTENDEDFORMATRANGEMINUTES {
            get {
                return ResourceManager.GetString("ERROR_EXTENDEDFORMATRANGEMINUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes del año en ExtendedFormat fuera de rango..
        /// </summary>
        internal static string ERROR_EXTENDEDFORMATRANGEMONTHS {
            get {
                return ResourceManager.GetString("ERROR_EXTENDEDFORMATRANGEMONTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha especificado un nombre de archivo de configuración externo..
        /// </summary>
        internal static string ERROR_FILECONFIGURATIONSOURCE_FILENAME_NOTSPECIFIEDINCONFIGURATION {
            get {
                return ResourceManager.GetString("ERROR_FILECONFIGURATIONSOURCE_FILENAME_NOTSPECIFIEDINCONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado el archivo de configuración externo &quot;{0}&quot;..
        /// </summary>
        internal static string ERROR_FILECONFIGURATIONSOURCE_FILENOTFOUND {
            get {
                return ResourceManager.GetString("ERROR_FILECONFIGURATIONSOURCE_FILENOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No todos los objetos DbCommands son válidos..
        /// </summary>
        internal static string ERROR_GENERICDATABASE_INVALIDCOMMANDS {
            get {
                return ResourceManager.GetString("ERROR_GENERICDATABASE_INVALIDCOMMANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parámetro &quot;{0}&quot; no contiene ningún nombre de tabla..
        /// </summary>
        internal static string ERROR_GENERICDATABASE_TABLENAMEARRAYEMPTY {
            get {
                return ResourceManager.GetString("ERROR_GENERICDATABASE_TABLENAMEARRAYEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor no puede ser nulo o cadena vacía..
        /// </summary>
        internal static string ERROR_GENERICDATABASE_TABLENAMENULLOREMPTY {
            get {
                return ResourceManager.GetString("ERROR_GENERICDATABASE_TABLENAMENULLOREMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo &quot;{0}&quot; no no existe..
        /// </summary>
        internal static string ERROR_INVALIDFILENAME {
            get {
                return ResourceManager.GetString("ERROR_INVALIDFILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay permiso para Permission para UnmanagedCode..
        /// </summary>
        internal static string ERROR_LOGENTRY_INTRINSICPPROPERTYNOUNMANAGEDCODEPERMISSION {
            get {
                return ResourceManager.GetString("ERROR_LOGENTRY_INTRINSICPPROPERTYNOUNMANAGEDCODEPERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo leer la propiedad intrínsica. mensaje: {0}.
        /// </summary>
        internal static string ERROR_LOGENTRY_INTRINSICPROPERTY {
            get {
                return ResourceManager.GetString("ERROR_LOGENTRY_INTRINSICPROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la configuración del categorySources  &quot;{0}&quot;.
        /// </summary>
        internal static string ERROR_LOGGINGLOGSOURCEFACTORY_CONFIGURATIONLOGSOURCENOTFOUND {
            get {
                return ResourceManager.GetString("ERROR_LOGGINGLOGSOURCEFACTORY_CONFIGURATIONLOGSOURCENOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la configuración del filtro &quot;{0}&quot;.
        /// </summary>
        internal static string ERROR_LOGINFILTERFACTORY_CONFIGURATIONFILTERNOTFOUND {
            get {
                return ResourceManager.GetString("ERROR_LOGINFILTERFACTORY_CONFIGURATIONFILTERNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falta la sección de configuración..
        /// </summary>
        internal static string ERROR_LOGINFILTERFACTORY_CONFIGURATIONNOTFOUND {
            get {
                return ResourceManager.GetString("ERROR_LOGINFILTERFACTORY_CONFIGURATIONNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la configuración del listener &quot;{0}&quot;.
        /// </summary>
        internal static string ERROR_LOGINLISTENERFACTORY_CONFIGURATIONLISTENERNOTFOUND {
            get {
                return ResourceManager.GetString("ERROR_LOGINLISTENERFACTORY_CONFIGURATIONLISTENERNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de archivo no puede ser nulo..
        /// </summary>
        internal static string ERROR_NULLFILENAME {
            get {
                return ResourceManager.GetString("ERROR_NULLFILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha inicializado la instancia de cache..
        /// </summary>
        internal static string ERROR_REALCACHE_NOTINITIALIZED {
            get {
                return ResourceManager.GetString("ERROR_REALCACHE_NOTINITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se especificó el parámetro &quot;{0}&quot; a usar por el &quot;SQLCacheManager&quot;..
        /// </summary>
        internal static string ERROR_SQLCACHEMANAGER_NULLPARAMETER {
            get {
                return ResourceManager.GetString("ERROR_SQLCACHEMANAGER_NULLPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra el catálogo con el nombre &quot;{0}&quot;. Verifique las cadenas de conexiones en el archivo de configuración..
        /// </summary>
        internal static string ERROR_SQLCONFIGURATIONSOURCE_CATALOGNAMENOTFOUND {
            get {
                return ResourceManager.GetString("ERROR_SQLCONFIGURATIONSOURCE_CATALOGNAMENOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha especificado el nombre del catálogo externo..
        /// </summary>
        internal static string ERROR_SQLCONFIGURATIONSOURCE_CATALOGNAMENOTSPECIFIED {
            get {
                return ResourceManager.GetString("ERROR_SQLCONFIGURATIONSOURCE_CATALOGNAMENOTSPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La configuración es incorrecta, se esperaba &quot;connStringName&quot;..
        /// </summary>
        internal static string ERROR_SQLCUSTOMTRACELISTENER_INVALIDCONFIGURATION {
            get {
                return ResourceManager.GetString("ERROR_SQLCUSTOMTRACELISTENER_INVALIDCONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El comando debe ser SQLCommand..
        /// </summary>
        internal static string ERROR_SQLDATABASE_NOTSQLCOMMAND {
            get {
                return ResourceManager.GetString("ERROR_SQLDATABASE_NOTSQLCOMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La exception arrojada fue: {0}.
        /// </summary>
        internal static string EVENTLOGEENTRYEXCEPTIONTEMPLATE {
            get {
                return ResourceManager.GetString("EVENTLOGEENTRYEXCEPTIONTEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ha ocurrido un error en la aplicación {0} en el {1}..
        /// </summary>
        internal static string EVENTLOGENTRYHEADERTEMPLATE {
            get {
                return ResourceManager.GetString("EVENTLOGENTRYHEADERTEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador de la actIvidad.
        /// </summary>
        internal static string LOG_ACTIVITYID {
            get {
                return ResourceManager.GetString("LOG_ACTIVITYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominio de aplicación.
        /// </summary>
        internal static string LOG_APPDOMAIN {
            get {
                return ResourceManager.GetString("LOG_APPDOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de las categorías.
        /// </summary>
        internal static string LOG_CATEGORIES {
            get {
                return ResourceManager.GetString("LOG_CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensajes de error.
        /// </summary>
        internal static string LOG_ERRORMESSAGES {
            get {
                return ResourceManager.GetString("LOG_ERRORMESSAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador del evento.
        /// </summary>
        internal static string LOG_EVENTID {
            get {
                return ResourceManager.GetString("LOG_EVENTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedades Extendidas.
        /// </summary>
        internal static string LOG_EXTENDEDPROPERTIES {
            get {
                return ResourceManager.GetString("LOG_EXTENDEDPROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del equipo.
        /// </summary>
        internal static string LOG_MACHINENAME {
            get {
                return ResourceManager.GetString("LOG_MACHINENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del hilo de ejecución .NET.
        /// </summary>
        internal static string LOG_MANAGERTHREADNAME {
            get {
                return ResourceManager.GetString("LOG_MANAGERTHREADNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuerpo del mensaje.
        /// </summary>
        internal static string LOG_MESSAGE {
            get {
                return ResourceManager.GetString("LOG_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioridad.
        /// </summary>
        internal static string LOG_PRIORITY {
            get {
                return ResourceManager.GetString("LOG_PRIORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador de proceso..
        /// </summary>
        internal static string LOG_PROCESSID {
            get {
                return ResourceManager.GetString("LOG_PROCESSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del proceso.
        /// </summary>
        internal static string LOG_PROCESSNAME {
            get {
                return ResourceManager.GetString("LOG_PROCESSNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador de la actividad relacionada.
        /// </summary>
        internal static string LOG_RELATEDACTIVITYID {
            get {
                return ResourceManager.GetString("LOG_RELATEDACTIVITYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de evento.
        /// </summary>
        internal static string LOG_SEVERITY {
            get {
                return ResourceManager.GetString("LOG_SEVERITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha y hora.
        /// </summary>
        internal static string LOG_TIMESTAMP {
            get {
                return ResourceManager.GetString("LOG_TIMESTAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        internal static string LOG_TITLE {
            get {
                return ResourceManager.GetString("LOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador del proceso Win32.
        /// </summary>
        internal static string LOG_WIN32THREADID {
            get {
                return ResourceManager.GetString("LOG_WIN32THREADID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin de traza: Actividad &apos;{0}&apos; en método &apos;{1}&apos; .
        /// </summary>
        internal static string TRACER_ENDMESSAGEFORMAT {
            get {
                return ResourceManager.GetString("TRACER_ENDMESSAGEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comienzo de traza: Actividad &apos;{0}&apos; en método &apos;{1}&apos;.
        /// </summary>
        internal static string TRACER_STARTMESSAGEFORMAT {
            get {
                return ResourceManager.GetString("TRACER_STARTMESSAGEFORMAT", resourceCulture);
            }
        }

       internal static string ERROR_AUTHENTICATORFACTORY_INVALIDDEFAULTCACHEMANAGERNAME
        {
            get {
                return ResourceManager.GetString("ERROR_AUTHENTICATORFACTORY_INVALIDDEFAULTCACHEMANAGERNAME", resourceCulture);
            }
        }


        
    }
}
